version: 2

project_name: dis

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: dis
    ldflags:
      - -s -w

archives:
  - id: binary
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

  - id: packages
    format: tar.gz
    name_template: "{{ .ProjectName }}_packages"
    files:
      - packages/**/*
    meta: true

checksum:
  name_template: checksums.txt

release:
  github:
    owner: napicella
    name: dis
