### -- Manifest
### provides: common/eza
### depends_on: [tools/cargo]
### distro: [all]
### -- End

# https://github.com/eza-community/eza - modern alternative to file listing

if [[ -n "${DIS_INSTALL:-}" ]]; then
  echo "Installing eza via cargo..."
  cargo install --locked eza
fi

# MIGRATION(2026-10-01): one-time cleanup; drop once every host has run dis config since then.
# This package used to be tools/eza, which locked the section under that name. dis
# skips sections locked by another owner, so release the old lock once.
if grep -qF '# BEGIN ls aliases import generated by dis config [locked by tools/eza]' \
    "${HOME}/rc/configs-generated/bash_aliases" 2> /dev/null; then
  dis tools rm-rc-section --file bash_aliases --name 'ls aliases' --owner 'tools/eza'
fi

dis tools add-rc-aliases \
  --name 'ls aliases' \
  --owner 'common/eza' \
  --content "$(cat <<'EOF'
if command -v eza &>/dev/null; then
  alias ls="eza --icons=auto"
  alias ll="eza -la --icons=auto"
fi
EOF
)"
