// Package rcstate keeps the sections of the generated rc files
// (~/rc/configs-generated/*) in a state file, the source of truth, and renders
// the files from it. dis is the only writer of those files: an edit made to
// them outside dis is backed up and overwritten on the next write.
package rcstate

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"iter"
	"os"
	"path/filepath"
	"strings"
	"syscall"
	"time"

	"github.com/napicella/dis/internal/tools"
	"gopkg.in/yaml.v3"
)

// Files are the generated rc files, in the order dis renders them.
var Files = []string{"bash_env", "bash_paths", "bash_aliases", "bash_init"}

const version = 1

// header starts every rendered file.
const header = `# Generated by dis from ~/.local/share/dis/sections.yaml. Don't edit:
# changes are overwritten. Use 'dis tools add-rc-*' and 'rm-rc-section'.
`

// Section is a named block of shell code in a generated file.
type Section struct {
	Name string `yaml:"name"`
	// Owner is the package whose installer wrote the section; empty when it
	// was written outside an installer.
	Owner string `yaml:"owner,omitempty"`
	// Locked sections can only be overwritten or removed by their owner.
	Locked  bool   `yaml:"locked,omitempty"`
	Content string `yaml:"content"`
}

// State is the content of the state file.
type State struct {
	Version int `yaml:"version"`
	// Files maps each generated file to its sections, in render order.
	Files map[string][]Section `yaml:"files"`
	// Rendered maps each generated file to the hash of the bytes dis last
	// wrote to it, to tell an edit made outside dis from a file that is only
	// behind the state.
	Rendered map[string]string `yaml:"rendered,omitempty"`
}

func newState() *State {
	return &State{Version: version, Files: map[string][]Section{}, Rendered: map[string]string{}}
}

// ErrCorrupt is returned by Load when the state file can't be read.
var ErrCorrupt = errors.New("state file is corrupt")

// ErrLocked is returned when a section is locked by another owner.
var ErrLocked = errors.New("section is locked by another owner")

// Upsert adds sec to file, or replaces the section with the same name in
// place. The last writer wins, unless the section is locked by another owner:
// then nothing changes and Upsert returns an error wrapping ErrLocked.
func (st *State) Upsert(file string, sec Section) error {
	secs := st.Files[file]
	for i, s := range secs {
		if s.Name != sec.Name {
			continue
		}
		if s.Locked && s.Owner != sec.Owner {
			return fmt.Errorf("%q in %s: %w (%s)", sec.Name, file, ErrLocked, s.Owner)
		}
		secs[i] = sec
		return nil
	}
	st.Files[file] = append(secs, sec)
	return nil
}

// Remove deletes the section name from file, if it is there. A section locked
// by an owner other than owner is kept, and Remove returns an error wrapping
// ErrLocked.
func (st *State) Remove(file, name, owner string) error {
	secs := st.Files[file]
	for i, s := range secs {
		if s.Name != name {
			continue
		}
		if s.Locked && s.Owner != owner {
			return fmt.Errorf("%q in %s: %w (%s)", name, file, ErrLocked, s.Owner)
		}
		st.Files[file] = append(secs[:i:i], secs[i+1:]...)
		return nil
	}
	return nil
}

// All yields every section with its file: the files in Files order, the
// sections of each in render order.
func (st *State) All() iter.Seq2[string, Section] {
	return func(yield func(string, Section) bool) {
		for _, file := range Files {
			for _, s := range st.Files[file] {
				if !yield(file, s) {
					return
				}
			}
		}
	}
}

// Render returns the content of file rendered from st.
func Render(st *State, file string) []byte {
	var b bytes.Buffer
	b.WriteString(header)
	for _, s := range st.Files[file] {
		b.WriteByte('\n')
		b.WriteString(tools.BeginMarker(s.Name, s.Owner, s.Locked))
		b.WriteByte('\n')
		if s.Content != "" {
			b.WriteString(s.Content)
			b.WriteByte('\n')
		}
		b.WriteString(tools.EndMarker(s.Name))
		b.WriteByte('\n')
	}
	return b.Bytes()
}

func hash(b []byte) string {
	sum := sha256.Sum256(b)
	return "sha256:" + hex.EncodeToString(sum[:])
}

// Status is how a generated file on disk compares with the state.
type Status int

const (
	// InSync: the file is what the state renders.
	InSync Status = iota
	// Missing: the file doesn't exist or is empty, so there's nothing to lose.
	Missing
	// Behind: the file is what dis last wrote, but the state has changed
	// since, e.g. after a crash between saving the state and rendering.
	Behind
	// Edited: the file changed after dis last wrote it.
	Edited
)

// Store reads and writes the state file and renders the generated files.
type Store struct {
	// StatePath is the state file, ~/.local/share/dis/sections.yaml.
	StatePath string
	// Dir holds the generated files, ~/rc/configs-generated.
	Dir string
	// Warn receives warnings, e.g. about edits made outside dis.
	Warn io.Writer
	// Now is the clock used for backup names.
	Now func() time.Time
}

// DefaultStore returns the Store for the current user's home directory.
func DefaultStore() (*Store, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return nil, fmt.Errorf("resolving home directory: %w", err)
	}
	return &Store{
		StatePath: filepath.Join(home, ".local", "share", "dis", "sections.yaml"),
		Dir:       filepath.Join(home, "rc", "configs-generated"),
		Warn:      os.Stderr,
		Now:       time.Now,
	}, nil
}

// Path returns the path of the generated file.
func (s *Store) Path(file string) string { return filepath.Join(s.Dir, file) }

// Load returns the state. Without a state file it imports the generated files
// in memory, writes nothing, and reports imported.
func (s *Store) Load() (st *State, imported bool, err error) {
	st, err = s.readState()
	if errors.Is(err, os.ErrNotExist) {
		st, _, err := s.importFiles()
		return st, true, err
	}
	return st, false, err
}

// readState reads the state file. A missing one gives an error matching
// os.ErrNotExist, one that can't be decoded an error wrapping ErrCorrupt.
func (s *Store) readState() (*State, error) {
	data, err := os.ReadFile(s.StatePath)
	if err != nil {
		return nil, err
	}
	st := newState()
	if err := yaml.Unmarshal(data, st); err != nil {
		return nil, fmt.Errorf("%w: %s: %v", ErrCorrupt, s.StatePath, err)
	}
	if st.Version != version {
		return nil, fmt.Errorf("%s has version %d, this dis reads version %d", s.StatePath, st.Version, version)
	}
	if st.Files == nil {
		st.Files = map[string][]Section{}
	}
	if st.Rendered == nil {
		st.Rendered = map[string]string{}
	}
	return st, nil
}

// importFiles builds a state from the sections of the generated files, and
// returns, per file, the lines outside sections that it couldn't import.
func (s *Store) importFiles() (*State, map[string][]string, error) {
	st := newState()
	skipped := map[string][]string{}
	headerLines := map[string]bool{}
	for _, l := range strings.Split(strings.TrimSpace(header), "\n") {
		headerLines[l] = true
	}
	for _, file := range Files {
		data, err := os.ReadFile(s.Path(file))
		if errors.Is(err, os.ErrNotExist) {
			continue
		}
		if err != nil {
			return nil, nil, err
		}
		lines := strings.Split(string(data), "\n")
		sections, outside := tools.ParseRC(lines)
		for _, sec := range sections {
			// Ignore an error: a locked duplicate keeps the first one.
			_ = st.Upsert(file, Section{Name: sec.Name, Owner: sec.Owner, Locked: sec.Locked, Content: sec.Content})
		}
		for _, i := range outside {
			if !headerLines[lines[i]] {
				skipped[file] = append(skipped[file], lines[i])
			}
		}
	}
	return st, skipped, nil
}

// Status reports how the generated file on disk compares with st.
func (s *Store) Status(st *State, file string) (Status, error) {
	disk, err := os.ReadFile(s.Path(file))
	switch {
	case errors.Is(err, os.ErrNotExist):
		return Missing, nil
	case err != nil:
		return 0, err
	case bytes.Equal(disk, Render(st, file)):
		return InSync, nil
	case len(disk) == 0:
		return Missing, nil
	case st.Rendered[file] == hash(disk):
		return Behind, nil
	}
	return Edited, nil
}

// Update locks the state file, loads the state (importing the generated files
// the first time), applies fn, saves the state and renders the generated
// files. A file edited outside dis is backed up before it's overwritten.
func (s *Store) Update(fn func(*State) error) error {
	return s.update(fn, false)
}

// UpdateKeepingEdits is Update, except that files edited outside dis are
// left as they are.
func (s *Store) UpdateKeepingEdits(fn func(*State) error) error {
	return s.update(fn, true)
}

func (s *Store) update(fn func(*State) error, keepEdited bool) error {
	if err := os.MkdirAll(filepath.Dir(s.StatePath), 0o755); err != nil {
		return err
	}
	unlock, err := lock(s.StatePath + ".lock")
	if err != nil {
		return err
	}
	defer unlock()

	st, err := s.readState()
	if errors.Is(err, ErrCorrupt) {
		// Rebuild from the rendered files, which carry the markers.
		bak, bakErr := Backup(s.StatePath, s.Now())
		if bakErr != nil {
			return err
		}
		if err := os.Remove(s.StatePath); err != nil {
			return err
		}
		fmt.Fprintf(s.Warn, "dis: %v; saved it to %s and rebuilt it from the generated files\n", err, bak)
		st, err = s.readState()
	}
	if errors.Is(err, os.ErrNotExist) {
		var skipped map[string][]string
		if st, skipped, err = s.importFiles(); err == nil {
			err = s.migrate(st, skipped)
		}
	}
	if err != nil {
		return err
	}
	if err := fn(st); err != nil {
		return err
	}
	if err := s.save(st); err != nil {
		return err
	}

	if err := os.MkdirAll(s.Dir, 0o755); err != nil {
		return err
	}
	for _, file := range Files {
		status, err := s.Status(st, file)
		if err != nil {
			return err
		}
		switch status {
		case InSync:
			st.Rendered[file] = hash(Render(st, file))
			continue
		case Edited:
			if keepEdited {
				continue
			}
			bak, err := Backup(s.Path(file), s.Now())
			if err != nil {
				return fmt.Errorf("backing up %s: %w", s.Path(file), err)
			}
			fmt.Fprintf(s.Warn, "dis: %s was edited outside dis; saved it to %s, then regenerated it\n", s.Path(file), bak)
		}
		out := Render(st, file)
		if err := tools.WriteFileAtomic(s.Path(file), out, 0o644); err != nil {
			return err
		}
		st.Rendered[file] = hash(out)
	}
	return s.save(st)
}

// migrate prepares a state imported from today's generated files: it backs up
// the files and records their hashes, so the first render replaces them
// without reporting them as edited. skipped are the lines importFiles
// couldn't import, per file, to warn about.
func (s *Store) migrate(st *State, skipped map[string][]string) error {
	var backups []string
	for _, file := range Files {
		data, err := os.ReadFile(s.Path(file))
		if err != nil || len(data) == 0 {
			continue
		}
		bak, err := Backup(s.Path(file), s.Now())
		if err != nil {
			return fmt.Errorf("backing up %s: %w", s.Path(file), err)
		}
		backups = append(backups, bak)
		st.Rendered[file] = hash(data)
		if n := len(skipped[file]); n > 0 {
			fmt.Fprintf(s.Warn, "dis: %d lines of %s are outside any section and were not kept; they are in %s\n", n, s.Path(file), bak)
		}
	}
	if len(backups) > 0 {
		fmt.Fprintf(s.Warn, "dis: the generated rc files are now rendered from %s; the previous files are in %s\n", s.StatePath, strings.Join(backups, ", "))
	}
	return nil
}

func (s *Store) save(st *State) error {
	var b bytes.Buffer
	enc := yaml.NewEncoder(&b)
	enc.SetIndent(2)
	if err := enc.Encode(st); err != nil {
		return err
	}
	if err := enc.Close(); err != nil {
		return err
	}
	return tools.WriteFileAtomic(s.StatePath, b.Bytes(), 0o644)
}

// lock takes an exclusive lock on path, creating it, and returns the function
// that releases it.
func lock(path string) (func(), error) {
	f, err := os.OpenFile(path, os.O_CREATE|os.O_RDWR, 0o644)
	if err != nil {
		return nil, err
	}
	if err := syscall.Flock(int(f.Fd()), syscall.LOCK_EX); err != nil {
		f.Close()
		return nil, fmt.Errorf("locking %s: %w", path, err)
	}
	return func() { f.Close() }, nil
}

// Backup copies path to path.bak-<timestamp>, with the same permissions, and
// returns the copy's path. It never overwrites an earlier backup: a second
// one in the same second gets a "-2" suffix, and so on.
func Backup(path string, now time.Time) (string, error) {
	info, err := os.Stat(path)
	if err != nil {
		return "", err
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	base := path + ".bak-" + now.Format("20060102-150405")
	dst := base
	for n := 2; ; n++ {
		if _, err := os.Lstat(dst); errors.Is(err, os.ErrNotExist) {
			break
		}
		dst = fmt.Sprintf("%s-%d", base, n)
	}
	return dst, tools.WriteFileAtomic(dst, data, info.Mode().Perm())
}
