package rcstate

import (
	"bytes"
	"errors"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
	"time"
)

var now = time.Date(2026, 10, 2, 11, 0, 0, 0, time.UTC)

func newStore(t *testing.T) (*Store, *bytes.Buffer) {
	t.Helper()
	root := t.TempDir()
	var warn bytes.Buffer
	return &Store{
		StatePath: filepath.Join(root, "share", "sections.yaml"),
		Dir:       filepath.Join(root, "rc", "configs-generated"),
		Warn:      &warn,
		Now:       func() time.Time { return now },
	}, &warn
}

func write(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func read(t *testing.T, path string) string {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(b)
}

func names(secs []Section) []string {
	var out []string
	for _, s := range secs {
		out = append(out, s.Name)
	}
	return out
}

func upsert(file string, sec Section) func(*State) error {
	return func(st *State) error { return st.Upsert(file, sec) }
}

func TestUpsertKeepsOrder(t *testing.T) {
	st := newState()
	for _, n := range []string{"A", "B", "C"} {
		if err := st.Upsert("bash_paths", Section{Name: n, Content: "old"}); err != nil {
			t.Fatal(err)
		}
	}
	if err := st.Upsert("bash_paths", Section{Name: "A", Owner: "p", Content: "new"}); err != nil {
		t.Fatal(err)
	}
	secs := st.Files["bash_paths"]
	if got := names(secs); !reflect.DeepEqual(got, []string{"A", "B", "C"}) {
		t.Errorf("order = %v", got)
	}
	if secs[0] != (Section{Name: "A", Owner: "p", Content: "new"}) {
		t.Errorf("A = %+v", secs[0])
	}
}

func TestLocks(t *testing.T) {
	st := newState()
	locked := Section{Name: "ls", Owner: "common/eza", Locked: true, Content: "alias ls=eza"}
	if err := st.Upsert("bash_aliases", locked); err != nil {
		t.Fatal(err)
	}
	if err := st.Upsert("bash_aliases", Section{Name: "ls", Owner: "other", Content: "x"}); !errors.Is(err, ErrLocked) {
		t.Errorf("upsert by another owner: err = %v", err)
	}
	if err := st.Remove("bash_aliases", "ls", "other"); !errors.Is(err, ErrLocked) {
		t.Errorf("remove by another owner: err = %v", err)
	}
	if st.Files["bash_aliases"][0] != locked {
		t.Errorf("locked section changed: %+v", st.Files["bash_aliases"][0])
	}
	if err := st.Upsert("bash_aliases", Section{Name: "ls", Owner: "common/eza", Locked: true, Content: "y"}); err != nil {
		t.Errorf("upsert by the owner: %v", err)
	}
	if err := st.Remove("bash_aliases", "ls", "common/eza"); err != nil || len(st.Files["bash_aliases"]) != 0 {
		t.Errorf("remove by the owner: %v, %+v", err, st.Files["bash_aliases"])
	}
	if err := st.Remove("bash_aliases", "ls", ""); err != nil {
		t.Errorf("remove absent: %v", err)
	}
}

func TestRender(t *testing.T) {
	st := newState()
	st.Files["bash_paths"] = []Section{
		{Name: "A", Owner: "common/a", Content: "export A=1"},
		{Name: "B", Content: "x\n\ny"},
		{Name: "L", Owner: "common/l", Locked: true},
	}
	want := header + `
# BEGIN A import generated by dis config [owned by common/a]
export A=1
# END A import generated by dis config

# BEGIN B import generated by dis config
x

y
# END B import generated by dis config

# BEGIN L import generated by dis config [locked by common/l]
# END L import generated by dis config
`
	if got := string(Render(st, "bash_paths")); got != want {
		t.Errorf("got:\n%s\nwant:\n%s", got, want)
	}
	if got := string(Render(st, "bash_init")); got != header {
		t.Errorf("empty file: %q", got)
	}
}

func TestMigration(t *testing.T) {
	s, warn := newStore(t)
	paths := "# BEGIN Cargo import generated by dis config\nexport PATH=\"$HOME/.cargo/bin:$PATH\"\n# END Cargo import generated by dis config\n\n" +
		"stray line\n"
	aliases := "# BEGIN ls aliases import generated by dis config [locked by common/eza]\nalias ls=eza\n# END ls aliases import generated by dis config\n"
	write(t, s.Path("bash_paths"), paths)
	write(t, s.Path("bash_aliases"), aliases)

	if err := s.Update(upsert("bash_paths", Section{Name: "Mise", Owner: "common/mise", Content: "m"})); err != nil {
		t.Fatal(err)
	}
	st, imported, err := s.Load()
	if err != nil || imported {
		t.Fatalf("Load: imported %v, err %v", imported, err)
	}
	if got := st.Files["bash_paths"]; !reflect.DeepEqual(got, []Section{
		{Name: "Cargo", Content: `export PATH="$HOME/.cargo/bin:$PATH"`},
		{Name: "Mise", Owner: "common/mise", Content: "m"},
	}) {
		t.Errorf("bash_paths sections: %+v", got)
	}
	if got := st.Files["bash_aliases"]; !reflect.DeepEqual(got, []Section{{Name: "ls aliases", Owner: "common/eza", Locked: true, Content: "alias ls=eza"}}) {
		t.Errorf("bash_aliases sections: %+v", got)
	}
	for file, orig := range map[string]string{"bash_paths": paths, "bash_aliases": aliases} {
		if got := read(t, s.Path(file)+".bak-20261002-110000"); got != orig {
			t.Errorf("%s backup = %q", file, got)
		}
		if got := read(t, s.Path(file)); got != string(Render(st, file)) {
			t.Errorf("%s not rendered:\n%s", file, got)
		}
	}
	if got := read(t, s.Path("bash_init")); got != header {
		t.Errorf("bash_init = %q", got)
	}
	w := warn.String()
	if !strings.Contains(w, "1 lines of "+s.Path("bash_paths")+" are outside any section") || !strings.Contains(w, "now rendered from") {
		t.Errorf("warnings:\n%s", w)
	}
	if strings.Contains(w, "edited outside dis") {
		t.Errorf("migration reported an edit:\n%s", w)
	}

	// The rendered files can be imported again: the header isn't reported.
	if err := os.Remove(s.StatePath); err != nil {
		t.Fatal(err)
	}
	warn.Reset()
	if err := s.Update(func(*State) error { return nil }); err != nil {
		t.Fatal(err)
	}
	if strings.Contains(warn.String(), "outside any section") {
		t.Errorf("re-import reported the header:\n%s", warn.String())
	}
	if st2, _, _ := s.Load(); !reflect.DeepEqual(st2.Files, st.Files) {
		t.Errorf("re-import:\ngot  %+v\nwant %+v", st2.Files, st.Files)
	}
}

func TestStatusAndUpdate(t *testing.T) {
	s, warn := newStore(t)
	if err := s.Update(upsert("bash_paths", Section{Name: "A", Content: "a"})); err != nil {
		t.Fatal(err)
	}
	st, _, _ := s.Load()
	status := func() Status {
		t.Helper()
		got, err := s.Status(st, "bash_paths")
		if err != nil {
			t.Fatal(err)
		}
		return got
	}
	if got := status(); got != InSync {
		t.Fatalf("after update: %v", got)
	}

	// Behind: the state changed, the file is still what dis wrote.
	if err := st.Upsert("bash_paths", Section{Name: "B", Content: "b"}); err != nil {
		t.Fatal(err)
	}
	if got := status(); got != Behind {
		t.Errorf("state changed: %v, want Behind", got)
	}

	// Edited.
	write(t, s.Path("bash_paths"), read(t, s.Path("bash_paths"))+"echo mine\n")
	if got := status(); got != Edited {
		t.Errorf("edited: %v, want Edited", got)
	}

	// Missing, and empty (the wrapper touches missing files).
	write(t, s.Path("bash_paths"), "")
	if got := status(); got != Missing {
		t.Errorf("empty: %v, want Missing", got)
	}
	os.Remove(s.Path("bash_paths"))
	if got := status(); got != Missing {
		t.Errorf("deleted: %v, want Missing", got)
	}
	if warn.Len() != 0 {
		t.Errorf("warnings: %s", warn.String())
	}
}

func TestUpdateBacksUpEdits(t *testing.T) {
	s, warn := newStore(t)
	if err := s.Update(upsert("bash_paths", Section{Name: "A", Content: "a"})); err != nil {
		t.Fatal(err)
	}
	edited := read(t, s.Path("bash_paths")) + "echo mine\n"
	write(t, s.Path("bash_paths"), edited)

	// UpdateKeepingEdits leaves the file alone.
	if err := s.UpdateKeepingEdits(upsert("bash_paths", Section{Name: "B", Content: "b"})); err != nil {
		t.Fatal(err)
	}
	if read(t, s.Path("bash_paths")) != edited {
		t.Errorf("file:\n%s", read(t, s.Path("bash_paths")))
	}

	// Update backs it up and renders.
	if err := s.Update(func(*State) error { return nil }); err != nil {
		t.Fatal(err)
	}
	bak := s.Path("bash_paths") + ".bak-20261002-110000"
	if got := read(t, bak); got != edited {
		t.Errorf("backup = %q", got)
	}
	st, _, _ := s.Load()
	if got := read(t, s.Path("bash_paths")); got != string(Render(st, "bash_paths")) {
		t.Errorf("not rendered:\n%s", got)
	}
	if !strings.Contains(warn.String(), "edited outside dis; saved it to "+bak) {
		t.Errorf("warning: %q", warn.String())
	}
}

func TestCorruptStateIsRebuilt(t *testing.T) {
	s, warn := newStore(t)
	if err := s.Update(upsert("bash_paths", Section{Name: "A", Owner: "common/a", Content: "a"})); err != nil {
		t.Fatal(err)
	}
	write(t, s.StatePath, "files: [not: valid")
	if _, _, err := s.Load(); !errors.Is(err, ErrCorrupt) {
		t.Fatalf("Load: %v", err)
	}
	if err := s.Update(upsert("bash_paths", Section{Name: "B", Content: "b"})); err != nil {
		t.Fatal(err)
	}
	st, _, err := s.Load()
	if err != nil {
		t.Fatal(err)
	}
	if got := st.Files["bash_paths"]; !reflect.DeepEqual(got, []Section{{Name: "A", Owner: "common/a", Content: "a"}, {Name: "B", Content: "b"}}) {
		t.Errorf("rebuilt: %+v", got)
	}
	if got := read(t, s.StatePath+".bak-20261002-110000"); got != "files: [not: valid" {
		t.Errorf("corrupt state backup = %q", got)
	}
	if !strings.Contains(warn.String(), "rebuilt it from the generated files") {
		t.Errorf("warning: %q", warn.String())
	}
}

func TestBackupNeverOverwrites(t *testing.T) {
	path := filepath.Join(t.TempDir(), "f")
	write(t, path, "one")
	if err := os.Chmod(path, 0o600); err != nil {
		t.Fatal(err)
	}
	first, err := Backup(path, now)
	if err != nil {
		t.Fatal(err)
	}
	write(t, path, "two")
	second, err := Backup(path, now)
	if err != nil {
		t.Fatal(err)
	}
	if second != first+"-2" || read(t, first) != "one" || read(t, second) != "two" {
		t.Errorf("backups %s=%q %s=%q", first, read(t, first), second, read(t, second))
	}
	if info, _ := os.Stat(first); info.Mode().Perm() != 0o600 {
		t.Errorf("backup mode = %v, want 0600", info.Mode().Perm())
	}
}

func TestFiles(t *testing.T) {
	// bash_env comes first: bash_paths entries can use the variables it exports.
	if want := []string{"bash_env", "bash_paths", "bash_aliases", "bash_init"}; !reflect.DeepEqual(Files, want) {
		t.Errorf("Files = %q, want %q", Files, want)
	}

	// An update renders every file, bash_env included.
	s, _ := newStore(t)
	if err := s.Update(upsert("bash_env", Section{Name: "E", Owner: "common/e", Content: "export E=1"})); err != nil {
		t.Fatal(err)
	}
	st, _, _ := s.Load()
	for _, file := range Files {
		if got := read(t, s.Path(file)); got != string(Render(st, file)) {
			t.Errorf("%s not rendered:\n%s", file, got)
		}
	}
	if got := read(t, s.Path("bash_env")); !strings.Contains(got, "# BEGIN E import generated by dis config [owned by common/e]\nexport E=1\n") {
		t.Errorf("bash_env = %q", got)
	}
}

func TestAll(t *testing.T) {
	st := newState()
	for _, u := range []struct{ file, name string }{
		{"bash_init", "I"}, {"bash_env", "E1"}, {"bash_aliases", "A"}, {"bash_env", "E2"},
	} {
		if err := st.Upsert(u.file, Section{Name: u.name}); err != nil {
			t.Fatal(err)
		}
	}
	var got []string
	for file, s := range st.All() {
		got = append(got, file+"/"+s.Name)
	}
	if want := []string{"bash_env/E1", "bash_env/E2", "bash_aliases/A", "bash_init/I"}; !reflect.DeepEqual(got, want) {
		t.Errorf("All = %q, want %q", got, want)
	}
	for range st.All() {
		break // stopping early must not panic
	}
}
