package tools

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// SectionMarker is in every BEGIN and END line: "# BEGIN <name> import
// generated by dis config", optionally followed by "[owned by X]" or
// "[locked by X]".
const SectionMarker = " import generated by dis config"

// BeginMarker returns the opening line of a section. A section with an owner
// shows it: "[locked by owner]" when locked, "[owned by owner]" otherwise.
func BeginMarker(name, owner string, locked bool) string {
	line := "# BEGIN " + name + SectionMarker
	switch {
	case owner != "" && locked:
		return line + " [locked by " + owner + "]"
	case owner != "":
		return line + " [owned by " + owner + "]"
	}
	return line
}

// EndMarker returns the closing line of a section.
func EndMarker(name string) string {
	return "# END " + name + SectionMarker
}

// parseBegin returns the name, owner and lock of a BEGIN line, or ok false
// when line is not one.
func parseBegin(line string) (name, owner string, locked, ok bool) {
	rest, found := strings.CutPrefix(line, "# BEGIN ")
	if !found {
		return "", "", false, false
	}
	name, meta, found := strings.Cut(rest, SectionMarker)
	if !found {
		return "", "", false, false
	}
	for _, m := range []struct {
		prefix string
		locked bool
	}{{" [locked by ", true}, {" [owned by ", false}} {
		if o, found := strings.CutPrefix(meta, m.prefix); found {
			if o, found = strings.CutSuffix(o, "]"); found {
				return name, o, m.locked, true
			}
		}
	}
	return name, "", false, true
}

// RCSection is a BEGIN/END section of an rc file.
type RCSection struct {
	Name    string
	Owner   string
	Locked  bool
	Content string
	// Begin and End are the indexes of the BEGIN and END lines.
	Begin, End int
}

// ParseRC returns the BEGIN/END sections in lines, and the indexes of the
// non-blank lines outside them. A BEGIN without its END runs to the end of
// the file and is not returned as a section.
func ParseRC(lines []string) (sections []RCSection, outside []int) {
	for i := 0; i < len(lines); i++ {
		name, owner, locked, ok := parseBegin(lines[i])
		if !ok {
			if strings.TrimSpace(lines[i]) != "" {
				outside = append(outside, i)
			}
			continue
		}
		end := i + 1
		for end < len(lines) && lines[end] != EndMarker(name) {
			end++
		}
		if end == len(lines) {
			break
		}
		content := strings.Trim(strings.Join(lines[i+1:end], "\n"), "\n")
		sections = append(sections, RCSection{Name: name, Owner: owner, Locked: locked, Content: content, Begin: i, End: end})
		i = end
	}
	return sections, outside
}

// AddRCSection upserts a named section in the file at path.
//
// A section looks like:
//
//	# BEGIN <name> import generated by dis config
//	<content>
//	# END <name> import generated by dis config
//
// When owner is non-empty the BEGIN marker includes a lock suffix:
//
//	# BEGIN <name> import generated by dis config [locked by <owner>]
//
// A locked section can only be updated by the same owner. Any other caller
// will have its update skipped with a warning printed to stderr.
//
// Behaviour:
//   - If the section is not present, it is appended.
//   - If the section is present with identical content, nothing is done.
//   - If the section is locked by a different owner, the update is skipped.
//   - If the section is present with different content, it is replaced.
//
// The file and all its parent directories are created if they do not exist.
func AddRCSection(path, name, content, owner string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("creating parent directories for %q: %w", path, err)
	}

	// Ensure the file exists.
	f, err := os.OpenFile(path, os.O_CREATE|os.O_RDWR, 0o644)
	if err != nil {
		return fmt.Errorf("opening %q: %w", path, err)
	}
	f.Close()

	raw, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("reading %q: %w", path, err)
	}

	existing := string(raw)
	end := EndMarker(name)

	// Find any existing BEGIN line for this section, with or without an owner.
	// The marker without an owner is a prefix of the others, so searching for
	// it finds any form.
	baseBegin := BeginMarker(name, "", false)
	beginIdx := strings.Index(existing, baseBegin)

	if beginIdx != -1 {
		// Determine the actual BEGIN line (up to the next newline).
		lineEnd := strings.Index(existing[beginIdx:], "\n")
		var beginLine string
		if lineEnd == -1 {
			beginLine = existing[beginIdx:]
		} else {
			beginLine = existing[beginIdx : beginIdx+lineEnd]
		}

		// Check if the existing section is locked by a different owner.
		if _, existingOwner, isLocked, _ := parseBegin(beginLine); isLocked && existingOwner != owner {
			fmt.Fprintf(os.Stderr, "skipping section %q: locked by %q\n", name, existingOwner)
			return nil
		}
	}

	begin := BeginMarker(name, owner, owner != "")

	if beginIdx == -1 {
		// Section not present — append.
		return appendSection(path, existing, begin, content, end)
	}

	endIdx := strings.Index(existing, end)
	if endIdx == -1 {
		// Malformed file: BEGIN without END — treat as not present and append.
		return appendSection(path, existing, begin, content, end)
	}
	endIdx += len(end)

	// Extract the current section body (between BEGIN line and END, exclusive).
	// beginIdx points to the start of the BEGIN line; skip past the newline.
	bodyStart := strings.Index(existing[beginIdx:], "\n")
	if bodyStart == -1 {
		return appendSection(path, existing, begin, content, end)
	}
	bodyStart += beginIdx + 1
	body := existing[bodyStart : endIdx-len(end)]
	body = strings.TrimLeft(body, "\n")
	body = strings.TrimRight(body, "\n")

	if body == content {
		// Identical content — no-op (but update the BEGIN line if owner changed).
		if existing[beginIdx:beginIdx+len(begin)] == begin {
			return nil
		}
	}

	// Different content or owner changed — remove the old section and re-append.
	return appendSection(path, cutSection(existing, beginIdx, endIdx), begin, content, end)
}

// cutSection returns existing with the section spanning [beginIdx, endIdx)
// removed, collapsing the blank lines around it into a single separator.
func cutSection(existing string, beginIdx, endIdx int) string {
	before := existing[:beginIdx]
	after := existing[endIdx:]
	after = strings.TrimLeft(after, "\n")

	rebuilt := strings.TrimRight(before, "\n")
	if rebuilt == "" {
		return after
	}
	rebuilt += "\n"
	if after != "" {
		rebuilt += "\n" + after
	}
	return rebuilt
}

// appendSection writes the file content and appends the new section to it.
func appendSection(path, existing, begin, content, end string) error {
	var sb strings.Builder
	trimmed := strings.TrimRight(existing, "\n")
	if trimmed != "" {
		sb.WriteString(trimmed)
		sb.WriteString("\n\n") // blank line between existing content and new section
	}
	sb.WriteString(begin)
	sb.WriteString("\n")
	sb.WriteString(content)
	if !strings.HasSuffix(content, "\n") {
		sb.WriteString("\n")
	}
	sb.WriteString(end)
	sb.WriteString("\n")

	return os.WriteFile(path, []byte(sb.String()), 0o644)
}

// PathPrependContent returns bash_paths content that prepends dirs to PATH,
// skipping a dir PATH already has. Nested shells inherit PATH and source
// bash_paths again, so an unguarded prepend repeats every entry once per level.
//
// Dirs are written as given, so $HOME and the like expand when the file is
// sourced. A trailing slash is dropped so "dir/" and "dir" are the same entry.
// The first dir ends up first in PATH.
func PathPrependContent(dirs []string) string {
	lines := make([]string, 0, len(dirs))
	for i := len(dirs) - 1; i >= 0; i-- {
		dir := dirs[i]
		if len(dir) > 1 {
			dir = strings.TrimRight(dir, "/")
		}
		lines = append(lines, fmt.Sprintf(`case ":$PATH:" in *":%[1]s:"*) ;; *) export PATH="%[1]s:$PATH" ;; esac`, dir))
	}
	return strings.Join(lines, "\n")
}
