package tools

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const sectionMarkerFmt = "# %s import generated by dis config"

// sectionBegin returns the opening marker line for a named section.
// When owner is non-empty, the marker includes a [locked by <owner>] suffix.
func sectionBegin(name, owner string) string {
	base := fmt.Sprintf("# BEGIN "+sectionMarkerFmt[2:], name)
	if owner != "" {
		return base + " [locked by " + owner + "]"
	}
	return base
}

// sectionEnd returns the closing marker line for a named section.
func sectionEnd(name string) string {
	return fmt.Sprintf("# END "+sectionMarkerFmt[2:], name)
}

// lockedOwner parses the owner from a BEGIN line that contains [locked by <owner>].
// Returns ("", false) if the line is not locked.
func lockedOwner(beginLine string) (string, bool) {
	const prefix = " [locked by "
	idx := strings.Index(beginLine, prefix)
	if idx == -1 {
		return "", false
	}
	rest := beginLine[idx+len(prefix):]
	end := strings.Index(rest, "]")
	if end == -1 {
		return "", false
	}
	return rest[:end], true
}

// AddRCSection upserts a named section in the file at path.
//
// A section looks like:
//
//	# BEGIN <name> import generated by dis config
//	<content>
//	# END <name> import generated by dis config
//
// When owner is non-empty the BEGIN marker includes a lock suffix:
//
//	# BEGIN <name> import generated by dis config [locked by <owner>]
//
// A locked section can only be updated by the same owner. Any other caller
// will have its update skipped with a warning printed to stderr.
//
// Behaviour:
//   - If the section is not present, it is appended.
//   - If the section is present with identical content, nothing is done.
//   - If the section is locked by a different owner, the update is skipped.
//   - If the section is present with different content, it is replaced.
//
// The file and all its parent directories are created if they do not exist.
func AddRCSection(path, name, content, owner string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("creating parent directories for %q: %w", path, err)
	}

	// Ensure the file exists.
	f, err := os.OpenFile(path, os.O_CREATE|os.O_RDWR, 0o644)
	if err != nil {
		return fmt.Errorf("opening %q: %w", path, err)
	}
	f.Close()

	raw, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("reading %q: %w", path, err)
	}

	existing := string(raw)
	end := sectionEnd(name)

	// Find any existing BEGIN line for this section (locked or not).
	// The unlocked base marker is a prefix of the locked variant, so searching
	// for the base is sufficient to find either form.
	baseBegin := sectionBegin(name, "")
	beginIdx := strings.Index(existing, baseBegin)

	if beginIdx != -1 {
		// Determine the actual BEGIN line (up to the next newline).
		lineEnd := strings.Index(existing[beginIdx:], "\n")
		var beginLine string
		if lineEnd == -1 {
			beginLine = existing[beginIdx:]
		} else {
			beginLine = existing[beginIdx : beginIdx+lineEnd]
		}

		// Check if the existing section is locked by a different owner.
		if existingOwner, isLocked := lockedOwner(beginLine); isLocked && existingOwner != owner {
			fmt.Fprintf(os.Stderr, "skipping section %q: locked by %q\n", name, existingOwner)
			return nil
		}
	}

	begin := sectionBegin(name, owner)

	if beginIdx == -1 {
		// Section not present — append.
		return appendSection(path, existing, begin, content, end)
	}

	endIdx := strings.Index(existing, end)
	if endIdx == -1 {
		// Malformed file: BEGIN without END — treat as not present and append.
		return appendSection(path, existing, begin, content, end)
	}
	endIdx += len(end)

	// Extract the current section body (between BEGIN line and END, exclusive).
	// beginIdx points to the start of the BEGIN line; skip past the newline.
	bodyStart := strings.Index(existing[beginIdx:], "\n")
	if bodyStart == -1 {
		return appendSection(path, existing, begin, content, end)
	}
	bodyStart += beginIdx + 1
	body := existing[bodyStart : endIdx-len(end)]
	body = strings.TrimLeft(body, "\n")
	body = strings.TrimRight(body, "\n")

	if body == content {
		// Identical content — no-op (but update the BEGIN line if owner changed).
		if existing[beginIdx:beginIdx+len(begin)] == begin {
			return nil
		}
	}

	// Different content or owner changed — remove the old section and re-append.
	before := existing[:beginIdx]
	after := existing[endIdx:]
	after = strings.TrimLeft(after, "\n")

	rebuilt := strings.TrimRight(before, "\n")
	if rebuilt != "" {
		rebuilt += "\n"
	}
	if after != "" {
		rebuilt += "\n" + after
	}

	return appendSection(path, rebuilt, begin, content, end)
}

// appendSection writes the file content and appends the new section to it.
func appendSection(path, existing, begin, content, end string) error {
	var sb strings.Builder
	trimmed := strings.TrimRight(existing, "\n")
	if trimmed != "" {
		sb.WriteString(trimmed)
		sb.WriteString("\n\n") // blank line between existing content and new section
	}
	sb.WriteString(begin)
	sb.WriteString("\n")
	sb.WriteString(content)
	if !strings.HasSuffix(content, "\n") {
		sb.WriteString("\n")
	}
	sb.WriteString(end)
	sb.WriteString("\n")

	return os.WriteFile(path, []byte(sb.String()), 0o644)
}
