package tools

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const sectionMarkerFmt = "# %s import generated by dis config"

// sectionBegin returns the opening marker line for a named section.
func sectionBegin(name string) string {
	return fmt.Sprintf("# BEGIN "+sectionMarkerFmt[2:], name)
}

// sectionEnd returns the closing marker line for a named section.
func sectionEnd(name string) string {
	return fmt.Sprintf("# END "+sectionMarkerFmt[2:], name)
}

// AddRCSection upserts a named section in the file at path.
//
// A section looks like:
//
//	# BEGIN <name> import generated by dis config
//	<content>
//	# END <name> import generated by dis config
//
// Behaviour:
//   - If the section is not present, it is appended.
//   - If the section is present with identical content, nothing is done.
//   - If the section is present with different content, it is replaced.
//
// The file and all its parent directories are created if they do not exist.
func AddRCSection(path, name, content string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("creating parent directories for %q: %w", path, err)
	}

	// Ensure the file exists.
	f, err := os.OpenFile(path, os.O_CREATE|os.O_RDWR, 0o644)
	if err != nil {
		return fmt.Errorf("opening %q: %w", path, err)
	}
	f.Close()

	raw, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("reading %q: %w", path, err)
	}

	begin := sectionBegin(name)
	end := sectionEnd(name)
	existing := string(raw)

	beginIdx := strings.Index(existing, begin)
	if beginIdx == -1 {
		// Section not present — append.
		return appendSection(path, existing, begin, content, end)
	}

	endIdx := strings.Index(existing, end)
	if endIdx == -1 {
		// Malformed file: BEGIN without END — treat as not present and append.
		return appendSection(path, existing, begin, content, end)
	}
	endIdx += len(end)

	// Extract the current section body (between BEGIN and END, exclusive).
	body := existing[beginIdx+len(begin) : endIdx-len(end)]
	body = strings.TrimLeft(body, "\n")
	body = strings.TrimRight(body, "\n")

	if body == content {
		// Identical — no-op.
		return nil
	}

	// Different content — remove the old section (including a trailing newline
	// if present) and append the new one.
	before := existing[:beginIdx]
	after := existing[endIdx:]
	// Strip leading newlines from after so we can re-add exactly one blank
	// line separator between the retained content and the re-appended section.
	after = strings.TrimLeft(after, "\n")

	rebuilt := strings.TrimRight(before, "\n")
	if rebuilt != "" {
		rebuilt += "\n"
	}
	if after != "" {
		// Keep a blank line before whatever sections follow the removed one.
		rebuilt += "\n" + after
	}

	return appendSection(path, rebuilt, begin, content, end)
}

// appendSection writes the file content and appends the new section to it.
func appendSection(path, existing, begin, content, end string) error {
	var sb strings.Builder
	trimmed := strings.TrimRight(existing, "\n")
	if trimmed != "" {
		sb.WriteString(trimmed)
		sb.WriteString("\n\n") // blank line between existing content and new section
	}
	sb.WriteString(begin)
	sb.WriteString("\n")
	sb.WriteString(content)
	if !strings.HasSuffix(content, "\n") {
		sb.WriteString("\n")
	}
	sb.WriteString(end)
	sb.WriteString("\n")

	return os.WriteFile(path, []byte(sb.String()), 0o644)
}
