package tools

import (
	"os"
	"path/filepath"
	"testing"
)

func writeRC(t *testing.T, content string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), "bash_aliases")
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	return path
}

func readRC(t *testing.T, path string) string {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(b)
}

func TestRemoveRCSection(t *testing.T) {
	const (
		first = "# BEGIN A import generated by dis config\nalias a=1\n# END A import generated by dis config\n"
		mid   = "# BEGIN B import generated by dis config\nalias b=2\n# END B import generated by dis config\n"
		last  = "# BEGIN C import generated by dis config\nalias c=3\n# END C import generated by dis config\n"
	)
	all := first + "\n" + mid + "\n" + last

	tests := []struct {
		name    string
		initial string
		remove  string
		want    string
	}{
		{"first section", all, "A", mid + "\n" + last},
		{"middle section", all, "B", first + "\n" + last},
		{"last section", all, "C", first + "\n" + mid},
		{"only section", mid, "B", ""},
		{"absent section is a no-op", first, "Z", first},
		{"prefix of another section's name is not matched", mid, "", mid},
		{"longer name sharing a prefix is not matched",
			"# BEGIN Coder extra import generated by dis config\nx\n# END Coder extra import generated by dis config\n",
			"Coder",
			"# BEGIN Coder extra import generated by dis config\nx\n# END Coder extra import generated by dis config\n"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			path := writeRC(t, tt.initial)
			if err := RemoveRCSection(path, tt.remove, ""); err != nil {
				t.Fatalf("RemoveRCSection: %v", err)
			}
			if got := readRC(t, path); got != tt.want {
				t.Errorf("content mismatch\ngot:\n%q\nwant:\n%q", got, tt.want)
			}
		})
	}
}

func TestRemoveRCSectionMissingFile(t *testing.T) {
	path := filepath.Join(t.TempDir(), "absent")
	if err := RemoveRCSection(path, "A", ""); err != nil {
		t.Fatalf("RemoveRCSection on a missing file: %v", err)
	}
	if _, err := os.Stat(path); !os.IsNotExist(err) {
		t.Errorf("RemoveRCSection created %q; want it left absent", path)
	}
}

func TestRemoveRCSectionLocked(t *testing.T) {
	const locked = "# BEGIN A import generated by dis config [locked by tools/a]\nalias a=1\n# END A import generated by dis config\n"

	path := writeRC(t, locked)
	if err := RemoveRCSection(path, "A", "tools/other"); err != nil {
		t.Fatalf("RemoveRCSection by another owner: %v", err)
	}
	if got := readRC(t, path); got != locked {
		t.Errorf("section locked by another owner was modified:\n%q", got)
	}

	if err := RemoveRCSection(path, "A", "tools/a"); err != nil {
		t.Fatalf("RemoveRCSection by the owner: %v", err)
	}
	if got := readRC(t, path); got != "" {
		t.Errorf("owner could not remove its section, left:\n%q", got)
	}
}

func TestRemoveRCSectionMissingEnd(t *testing.T) {
	path := writeRC(t, "# BEGIN A import generated by dis config\nalias a=1\n")
	if err := RemoveRCSection(path, "A", ""); err == nil {
		t.Fatal("RemoveRCSection with no END marker: want error, got nil")
	}
}

// AddRCSection shares cutSection with RemoveRCSection, so replacing the first
// section must not leave a leading blank line behind.
func TestAddRCSectionReplaceFirst(t *testing.T) {
	path := writeRC(t, "# BEGIN A import generated by dis config\nold\n# END A import generated by dis config\n\n"+
		"# BEGIN B import generated by dis config\nb\n# END B import generated by dis config\n")
	if err := AddRCSection(path, "A", "new", ""); err != nil {
		t.Fatal(err)
	}
	want := "# BEGIN B import generated by dis config\nb\n# END B import generated by dis config\n\n" +
		"# BEGIN A import generated by dis config\nnew\n# END A import generated by dis config\n"
	if got := readRC(t, path); got != want {
		t.Errorf("content mismatch\ngot:\n%q\nwant:\n%q", got, want)
	}
}
