package tools

import (
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

func writeRC(t *testing.T, content string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), "bash_aliases")
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	return path
}

func readRC(t *testing.T, path string) string {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(b)
}

func TestBeginMarker(t *testing.T) {
	for _, tt := range []struct {
		owner  string
		locked bool
		want   string
	}{
		{"", false, "# BEGIN A import generated by dis config"},
		{"common/a", false, "# BEGIN A import generated by dis config [owned by common/a]"},
		{"common/a", true, "# BEGIN A import generated by dis config [locked by common/a]"},
	} {
		got := BeginMarker("A", tt.owner, tt.locked)
		if got != tt.want {
			t.Errorf("BeginMarker(%q, %v) = %q, want %q", tt.owner, tt.locked, got, tt.want)
		}
		if name, owner, locked, ok := parseBegin(got); !ok || name != "A" || owner != tt.owner || locked != tt.locked {
			t.Errorf("parseBegin(%q) = %q, %q, %v, %v", got, name, owner, locked, ok)
		}
	}
}

func TestParseRC(t *testing.T) {
	lines := strings.Split(`# header

# BEGIN A import generated by dis config [owned by common/a]
alias a=1

alias b=2
# END A import generated by dis config
stray
# BEGIN B import generated by dis config [locked by common/b]
# END B import generated by dis config
# BEGIN C import generated by dis config
unterminated`, "\n")
	sections, outside := ParseRC(lines)
	want := []RCSection{
		{Name: "A", Owner: "common/a", Content: "alias a=1\n\nalias b=2", Begin: 2, End: 6},
		{Name: "B", Owner: "common/b", Locked: true, Content: "", Begin: 8, End: 9},
	}
	if !reflect.DeepEqual(sections, want) {
		t.Errorf("sections:\ngot  %+v\nwant %+v", sections, want)
	}
	if wantOut := []int{0, 7}; !reflect.DeepEqual(outside, wantOut) {
		t.Errorf("outside = %v, want %v", outside, wantOut)
	}
}

// Replacing the first section must not leave a leading blank line behind.
func TestAddRCSectionReplaceFirst(t *testing.T) {
	path := writeRC(t, "# BEGIN A import generated by dis config\nold\n# END A import generated by dis config\n\n"+
		"# BEGIN B import generated by dis config\nb\n# END B import generated by dis config\n")
	if err := AddRCSection(path, "A", "new", ""); err != nil {
		t.Fatal(err)
	}
	want := "# BEGIN B import generated by dis config\nb\n# END B import generated by dis config\n\n" +
		"# BEGIN A import generated by dis config\nnew\n# END A import generated by dis config\n"
	if got := readRC(t, path); got != want {
		t.Errorf("content mismatch\ngot:\n%q\nwant:\n%q", got, want)
	}
}

func TestPathPrependContent(t *testing.T) {
	line := func(dir string) string {
		return `case ":$PATH:" in *":` + dir + `:"*) ;; *) export PATH="` + dir + `:$PATH" ;; esac`
	}
	tests := []struct {
		name string
		dirs []string
		want string
	}{
		{"one dir", []string{"/opt/bin"}, line("/opt/bin")},
		{"variables are kept literal", []string{"$HOME/.toolbox/bin"}, line("$HOME/.toolbox/bin")},
		{"trailing slash is dropped", []string{"$HOME/.local/share/env-manager/"}, line("$HOME/.local/share/env-manager")},
		{"root is kept", []string{"/"}, line("/")},
		{"first dir ends up first", []string{"/a", "/b"}, line("/b") + "\n" + line("/a")},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := PathPrependContent(tt.dirs); got != tt.want {
				t.Errorf("got:\n%s\nwant:\n%s", got, tt.want)
			}
		})
	}
}

// Sourcing the section again, as a nested shell does, must not repeat entries.
func TestPathPrependContentIsIdempotent(t *testing.T) {
	bash, err := exec.LookPath("bash")
	if err != nil {
		t.Skip("bash not found")
	}
	path := filepath.Join(t.TempDir(), "bash_paths")
	if err := AddRCSection(path, "Test", PathPrependContent([]string{"/a", "/b/"}), ""); err != nil {
		t.Fatal(err)
	}
	out, err := exec.Command(bash, "-c", `PATH=/usr/bin; . "$1"; . "$1"; printf %s "$PATH"`, "bash", path).Output()
	if err != nil {
		t.Fatal(err)
	}
	if got, want := string(out), "/a:/b:/usr/bin"; got != want {
		t.Errorf("PATH = %q, want %q", got, want)
	}
}
