package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/napicella/dis/internal/tools"
	"github.com/spf13/cobra"
)

var toolsCmd = &cobra.Command{
	Use:   "tools",
	Short: "Collection of helper tools for use inside installer scripts",
}

// ── GNOME shortcut ────────────────────────────────────────────────────────────

var createGnomeShortCmd = &cobra.Command{
	Use:   "create-gnome-shortcut",
	Short: "Create a GNOME keyboard shortcut.",
	Long: `Create a GNOME keyboard shortcut with the name provided. For example:
dis tools create-gnome-shortcut --name test-key --cmd date --bind "<Super>Insert"

creates a shortcut named "test-key" that runs "date" when pressing the keys Super + Insert.
`,
	RunE: createGnomeShortcutCmdFn,
}

var (
	name    string
	command string
	binding string
)

func init() {
	createGnomeShortCmd.Flags().StringVar(&name, "name", "", "shortcut name")
	createGnomeShortCmd.Flags().StringVar(&command, "cmd", "", "command to run")
	createGnomeShortCmd.Flags().StringVar(&binding, "bind", "", "keybinding (e.g. <Super>q)")

	createGnomeShortCmd.MarkFlagRequired("name")
	createGnomeShortCmd.MarkFlagRequired("cmd")
	createGnomeShortCmd.MarkFlagRequired("bind")

	toolsCmd.AddCommand(createGnomeShortCmd)

	// RC helpers
	toolsCmd.AddCommand(addRCInitCmd)
	toolsCmd.AddCommand(addRCPathCmd)
	toolsCmd.AddCommand(addRCAliasesCmd)
	toolsCmd.AddCommand(addHomeRCCmd)

	rootCmd.AddCommand(toolsCmd)
}

func createGnomeShortcutCmdFn(cmd *cobra.Command, _ []string) error {
	index, path, err := tools.CreateGNOMEShortcut(name, command, binding)
	if err != nil {
		return err
	}

	fmt.Println("Created shortcut:")
	fmt.Printf("  custom%d\n", index)
	fmt.Printf("  %s -> %s (%s)\n", binding, name, command)
	fmt.Printf("  path: %s\n", path)

	return nil
}

// ── RC helpers ────────────────────────────────────────────────────────────────

var (
	rcName    string
	rcContent string
)

// rcFlags registers --name and --content on a command and marks them required.
func rcFlags(cmd *cobra.Command) {
	cmd.Flags().StringVar(&rcName, "name", "", "section identifier (unique per file)")
	cmd.Flags().StringVar(&rcContent, "content", "", "content to write into the section")
	cmd.MarkFlagRequired("name")    //nolint:errcheck
	cmd.MarkFlagRequired("content") //nolint:errcheck
}

// rcFilePath returns $HOME/<rel>, failing if $HOME is unset.
func rcFilePath(rel string) (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("resolving home directory: %w", err)
	}
	return filepath.Join(home, rel), nil
}

var addRCInitCmd = &cobra.Command{
	Use:   "add-rc-init",
	Short: "Upsert a named section in ~/rc/configs-generated/bash_init",
	Long: `Upsert a named section in ~/rc/configs-generated/bash_init.

Sections are delimited by:
  # BEGIN <name> import generated by dis config
  <content>
  # END <name> import generated by dis config

If the section is absent it is appended. If it is present with identical
content it is left unchanged. If the content differs the section is replaced.

bash_init is intended for code that must run in interactive shells (e.g.
tool activation hooks). It is sourced by ~/.bashrc, not by the dis wrapper.

Example:
  dis tools add-rc-init \
    --name "Autojump" \
    --content '[[ -s ~/.autojump/etc/profile.d/autojump.sh ]] && source ~/.autojump/etc/profile.d/autojump.sh'
`,
	RunE: func(cmd *cobra.Command, _ []string) error {
		path, err := rcFilePath("rc/configs-generated/bash_init")
		if err != nil {
			return err
		}
		return tools.AddRCSection(path, rcName, rcContent)
	},
}

var addRCPathCmd = &cobra.Command{
	Use:   "add-rc-path",
	Short: "Upsert a named section in ~/rc/configs-generated/bash_paths",
	Long: `Upsert a named section in ~/rc/configs-generated/bash_paths.

bash_paths is sourced by the dis wrapper before each installer runs, so PATH
additions written here are available to subsequent installers in the same run.

Example:
  dis tools add-rc-path \
    --name "Mise path" \
    --content 'export PATH="$HOME/.local/share/mise/shims:$PATH"'
`,
	RunE: func(cmd *cobra.Command, _ []string) error {
		path, err := rcFilePath("rc/configs-generated/bash_paths")
		if err != nil {
			return err
		}
		return tools.AddRCSection(path, rcName, rcContent)
	},
}

var addRCAliasesCmd = &cobra.Command{
	Use:   "add-rc-aliases",
	Short: "Upsert a named section in ~/rc/configs-generated/bash_aliases",
	Long: `Upsert a named section in ~/rc/configs-generated/bash_aliases.

bash_aliases is sourced by the dis wrapper before each installer runs.

Examples:
  dis tools add-home-rc \
    --name 'alias change dir to the dis config folder' \
    --content "alias c='cd ${DIS_CONFIG_FOLDER}'"

  dis tools add-home-rc \
    --name 'alias change dir to the home folder' \
    --content "alias h='cd \${HOME}'"
`,
	RunE: func(cmd *cobra.Command, _ []string) error {
		path, err := rcFilePath("rc/configs-generated/bash_aliases")
		if err != nil {
			return err
		}
		return tools.AddRCSection(path, rcName, rcContent)
	},
}

var addHomeRCCmd = &cobra.Command{
	Use:   "add-home-rc",
	Short: "Upsert a named section in ~/.bashrc",
	Long: `Upsert a named section directly in ~/.bashrc.

Use this to wire the dotfiles .bashrc or similar top-level shell configuration
into the user's home ~/.bashrc. The file is created if it does not exist.

Example:
  dis tools add-home-rc \
    --name "bashrc" \
    --content 'if [ -f /path/to/dotfiles/.bashrc ]; then . /path/to/dotfiles/.bashrc; fi'
`,
	RunE: func(cmd *cobra.Command, _ []string) error {
		path, err := rcFilePath(".bashrc")
		if err != nil {
			return err
		}
		return tools.AddRCSection(path, rcName, rcContent)
	},
}

func init() {
	rcFlags(addRCInitCmd)
	rcFlags(addRCPathCmd)
	rcFlags(addRCAliasesCmd)
	rcFlags(addHomeRCCmd)
}
