# binding.sh
#
# Sourced by every installer via: source $DIS_BINDING
#
# The dis runner sets the following env vars before sourcing this file:
#   DIS_PKG_ROOT      - root directory of the package that owns this installer.
#                       When a dis.workspace file is present in the source dir,
#                       this is the resolved "root" entry for the package.
#                       Otherwise it equals the source directory itself.
#                       (e.g. /home/user/github/dis/packages/all)
#   DIS_CONFIG_FOLDER - (optional) configs directory for this package, as
#                       declared in the dis.workspace "configs" entry. Empty
#                       when no workspace file is present or no configs are
#                       declared for this package.
#   DIS_INSTALLER     - absolute path to the installer script being executed.
#                       (e.g. /home/user/github/dis/packages/all/installers/01_tmux.sh)
#   DIS_DISTRO        - os name from the distro YAML (e.g. "ubuntu")
#
# This file provides:
#   All bashrc_* helper functions

set -e

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#                                Private Functions                             #
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

function __bootstrap() {
  local RC_CFG_GEN_FOLDER="$HOME/rc/configs-generated"

  # DIS_CONFIG_FOLDER is set by the dis runner from the dis.workspace file.
  # Nothing to resolve here.

  # Create the directory to store the rc files generated by the installers.
  mkdir -p "$RC_CFG_GEN_FOLDER"
  touch "$RC_CFG_GEN_FOLDER/bash_paths"
  touch "$RC_CFG_GEN_FOLDER/bash_init"
  touch "$RC_CFG_GEN_FOLDER/bash_aliases"
  # Do not source bash_init which contains code made to be sourced in interactive sessions.
  source "$RC_CFG_GEN_FOLDER/bash_paths"
  source "$RC_CFG_GEN_FOLDER/bash_aliases"
}

# Private function.
# Adds instructions to the .bashrc in the home dir.
function __bashrc_home_add() {
  local SEARCH_STRING="# ${1} import generated by dis config"
  local CONFIG=$2
  local BASH_FILE="$HOME/.bashrc"

  if [ ! -f "$BASH_FILE" ]; then
    touch "$BASH_FILE"
  fi

  if ! grep -qF "$SEARCH_STRING" "$BASH_FILE"; then
      {
        echo "$SEARCH_STRING"
        echo "$CONFIG"
        echo
      } > "$BASH_FILE"
  fi
}

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#                                Public Functions                              #
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

# Add instructions that must be executed during bash initialization.
#
# Example usage:
# bashrc_init_add "Autojump" '[[ -s ~/.autojump/etc/profile.d/autojump.sh ]] && source ~/.autojump/etc/profile.d/autojump.sh'
function bashrc_init_add() {
  local SEARCH_STRING="# ${1} import generated by dis config"
  local CONFIG=$2
  local BASH_INIT="$HOME/rc/configs-generated/bash_init"

  if ! grep -qF "$SEARCH_STRING" "$BASH_INIT"; then
    {
      echo "$SEARCH_STRING"
      echo "$CONFIG"
      echo
    } >> "$BASH_INIT"
  fi
}

# Add path to the list of paths.
#
# Example usage:
# bashrc_path_add "Mise path" 'export PATH="$HOME/.local/share/mise/shims:$PATH"'
function bashrc_path_add() {
  local SEARCH_STRING="# ${1} import generated by dis config"
  local CONFIG=$2
  local BASH_PATHS="$HOME/rc/configs-generated/bash_paths"

  if ! grep -qF "$SEARCH_STRING" "$BASH_PATHS"; then
    {
      echo "$SEARCH_STRING"
      echo "$CONFIG"
    } >> "$BASH_PATHS"
  fi
}

# Add aliases that need to be sourced.
#
# Example usage:
# bashrc_aliases_add "Notifier" '[[ -s "${HOME}/.local/share/notifier/notifier_aliases" ]] && source "${HOME}/.local/share/notifier/notifier_aliases"'
function bashrc_aliases_add() {
  local SEARCH_STRING="# ${1} import generated by dis config"
  local CONFIG=$2
  local BASH_ALIASES="$HOME/rc/configs-generated/bash_aliases"

  if ! grep -qF "$SEARCH_STRING" "$BASH_ALIASES"; then
    {
      echo "$SEARCH_STRING"
      echo "$CONFIG"
    } >> "$BASH_ALIASES"
  fi
}

# Exports a KEY=VALUE pair to DIS_EXPORTS_FILE so that downstream installers
# that declare "provides:KEY" in requires_env can import it.
#
# Usage: dis_export KEY value
# Example: dis_export GID_DOCKER "$(getent group docker | cut -d: -f3)"
function dis_export() {
  local key="$1"
  local value="$2"
  if [ -z "${DIS_EXPORTS_FILE:-}" ]; then
    echo "dis_export: DIS_EXPORTS_FILE is not set" >&2
    return 1
  fi
  echo "${key}=${value}" >> "$DIS_EXPORTS_FILE"
}

__bootstrap
