# binding.sh
#
# Sourced by every installer via: source $DIS_BINDING
#
# The dis runner sets the following env vars before sourcing this file:
#   DIS_PKG_ROOT  - root of the source folder that contains this installer
#                   (e.g. dis/packages/ubuntu)
#   DIS_INSTALLER - absolute path to the installer script being executed;
#                   equivalent to $DIS_PKG_ROOT/<installers/.../<script>.sh>
#                   (e.g. dis/packages/ubuntu/installers/gui/03_fonts.sh)
#   DIS_DISTRO    - os name from the distro YAML (e.g. "ubuntu")
#
# This file provides:
#   1. DIS_CONFIG_FOLDER    - sibling configs/ of the installer's parent dir
#                             (e.g. dis/packages/all/installers/01_tmux.sh
#                              → dis/packages/all/configs)
#   2. All bashrc_* helper functions

set -e

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#                                Private Functions                             #
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

function __bootstrap() {
  local RC_CFG_GEN_FOLDER="$HOME/rc/configs-generated"

  # Resolve DIS_CONFIG_FOLDER from DIS_INSTALLER.
  # Convention: installer lives in <pkg>/installers/, configs in <pkg>/configs/.
  # e.g. dis/packages/all/installers/01_tmux.sh → dis/packages/all/configs
  if [ -n "$DIS_INSTALLER" ]; then
    local _pkg_dir
    _pkg_dir=$(dirname "$(dirname "$DIS_INSTALLER")")
    if [ -d "$_pkg_dir/configs" ]; then
      export DIS_CONFIG_FOLDER="$_pkg_dir/configs"
    fi
  fi

  # Create the directory to store the rc files generated by the installers.
  mkdir -p "$RC_CFG_GEN_FOLDER"
  touch "$RC_CFG_GEN_FOLDER/bash_paths"
  touch "$RC_CFG_GEN_FOLDER/bash_init"
  touch "$RC_CFG_GEN_FOLDER/bash_aliases"
  # Do not source bash_init which contains code made to be sourced in interactive sessions.
  source "$RC_CFG_GEN_FOLDER/bash_paths"
  source "$RC_CFG_GEN_FOLDER/bash_aliases"
}

# Private function.
# Adds instructions to the .bashrc in the home dir.
function __bashrc_home_add() {
  local SEARCH_STRING="# ${1} import generated by dis config"
  local CONFIG=$2
  local BASH_FILE="$HOME/.bashrc"

  if [ ! -f "$BASH_FILE" ]; then
    touch "$BASH_FILE"
  fi

  if ! grep -qF "$SEARCH_STRING" "$BASH_FILE"; then
      {
        echo "$SEARCH_STRING"
        echo "$CONFIG"
        echo
      } > "$BASH_FILE"
  fi
}

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#                                Public Functions                              #
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

# Add instructions that must be executed during bash initialization.
#
# Example usage:
# bashrc_init_add "Autojump" '[[ -s ~/.autojump/etc/profile.d/autojump.sh ]] && source ~/.autojump/etc/profile.d/autojump.sh'
function bashrc_init_add() {
  local SEARCH_STRING="# ${1} import generated by dis config"
  local CONFIG=$2
  local BASH_INIT="$HOME/rc/configs-generated/bash_init"

  if ! grep -qF "$SEARCH_STRING" "$BASH_INIT"; then
    {
      echo "$SEARCH_STRING"
      echo "$CONFIG"
      echo
    } >> "$BASH_INIT"
  fi
}

# Add path to the list of paths.
#
# Example usage:
# bashrc_path_add "Mise path" 'export PATH="$HOME/.local/share/mise/shims:$PATH"'
function bashrc_path_add() {
  local SEARCH_STRING="# ${1} import generated by dis config"
  local CONFIG=$2
  local BASH_PATHS="$HOME/rc/configs-generated/bash_paths"

  if ! grep -qF "$SEARCH_STRING" "$BASH_PATHS"; then
    {
      echo "$SEARCH_STRING"
      echo "$CONFIG"
    } >> "$BASH_PATHS"
  fi
}

# Add aliases that need to be sourced.
#
# Example usage:
# bashrc_aliases_add "Notifier" '[[ -s "${HOME}/.local/share/notifier/notifier_aliases" ]] && source "${HOME}/.local/share/notifier/notifier_aliases"'
function bashrc_aliases_add() {
  local SEARCH_STRING="# ${1} import generated by dis config"
  local CONFIG=$2
  local BASH_ALIASES="$HOME/rc/configs-generated/bash_aliases"

  if ! grep -qF "$SEARCH_STRING" "$BASH_ALIASES"; then
    {
      echo "$SEARCH_STRING"
      echo "$CONFIG"
    } >> "$BASH_ALIASES"
  fi
}

# Exports a KEY=VALUE pair to DIS_EXPORTS_FILE so that downstream installers
# that declare "provides:KEY" in requires_env can import it.
#
# Usage: dis_export KEY value
# Example: dis_export GID_DOCKER "$(getent group docker | cut -d: -f3)"
function dis_export() {
  local key="$1"
  local value="$2"
  if [ -z "${DIS_EXPORTS_FILE:-}" ]; then
    echo "dis_export: DIS_EXPORTS_FILE is not set" >&2
    return 1
  fi
  echo "${key}=${value}" >> "$DIS_EXPORTS_FILE"
}

__bootstrap
