# Reference
# ---------------------------------
# activate = ctrl + b
# ---------------------------------
# Create new tab
# <activate> + c
# ---------------------------------
# Switch to tab
# <activate> + <num>
# ---------------------------------
# Split horizontally
# <activate> + -
# ---------------------------------
# Split vertically
# <activate> + |
# ---------------------------------
# Move between panes
# alt + <arrow key>
# ---------------------------------
# Enter vi mode
# <activate> + [
# ---------------------------------
# Copy test from the buffer
# Enter vi mode or scroll wheel up
# start selection with space
# select lines with arrows
# press enter when done
# now text is in the system clipboard
# ---------------------------------
# Search down
# Enter vi mode
# /
# ---------------------------------
# Search up
# Enter vi mode
# shift + /
# ---------------------------------
# Create window
# <activate> + c
# ---------------------------------
# Rename window
# <activate> + ,
# ---------------------------------
# Switch to window
# <activate> + <index-number>

set -g terminal-overrides 'xterm*:smcup@:rmcup@'
set -g default-terminal "screen-256color"

unbind %

setw -g mouse on
set-window-option -g xterm-keys on
bind-key -n M-Down select-pane -D
bind-key -n M-Left select-pane -L
bind-key -n M-Right select-pane -R
bind-key -n M-Up select-pane -U

bind | split-window -h
bind - split-window -v
bind N break-pane

# Allow enabling vi mode
set -g mode-keys vi

# Allows copy test from the buffer
# Note: this only works if vi mode is enabled (i.e. set -g mode-keys vi)
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -i -f -selection primary | xclip -i -selection clipboard"


# Allows creating a window and giving it a name, overriding the default which just creates 
# the window with the name of the current executable
bind-key c command-prompt -p "window name:" "new-window; rename-window '%%'"

# DESIGN TWEAKS
#
# Note - tmux colors: https://superuser.com/questions/285381/how-does-the-tmux-color-palette-work

# Highlight active window
set -g mode-style bg=blue

# Set window notifications
setw -g monitor-activity on
set -g visual-activity on

# Automatically set window title
setw -g automatic-rename

# Pane borders
set -g pane-border-style 'fg=colour7'
set -g pane-active-border-style 'fg=colour93'
set -g pane-border-status bottom
set -g pane-border-format ''

# Status bar
set-option -g status on
set -g status-interval 5
set -g status-fg white
set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=colour93'
set -g status-left ''
set -g status-right '%Y-%m-%d %H:%M '
set -g status-right-length 50
set -g status-left-length 10

setw -g window-status-current-style 'fg=colour0 bg=colour93 bold'
setw -g window-status-current-format ' #I #W #F '
setw -g window-status-style 'fg=colour93 dim'
setw -g window-status-format ' #I #[fg=colour7]#W #[fg=colour93]#F '
setw -g window-status-bell-style 'fg=colour2 bg=colour1 bold'
