package doctor

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
	"time"

	"github.com/napicella/dis/internal/rcstate"
)

const disImport = `# BEGIN bash config import generated by dis config
[ -f ~/rc/bash_config.sh ] && source ~/rc/bash_config.sh;
# END bash config import generated by dis config
`

var now = time.Date(2026, 10, 2, 11, 0, 0, 0, time.UTC)

// newHome returns a temp home with files written into it, and its Store.
func newHome(t *testing.T, files map[string]string) (string, *rcstate.Store) {
	t.Helper()
	home := t.TempDir()
	for rel, content := range files {
		write(t, filepath.Join(home, rel), content)
	}
	return home, &rcstate.Store{
		StatePath: filepath.Join(home, ".local", "share", "dis", "sections.yaml"),
		Dir:       filepath.Join(home, "rc", "configs-generated"),
		Warn:      &bytes.Buffer{},
		Now:       func() time.Time { return now },
	}
}

func write(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func read(t *testing.T, path string) string {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(b)
}

// withSections writes sections through the store, as 'dis tools add-rc-*' does.
func withSections(t *testing.T, store *rcstate.Store, file string, secs ...rcstate.Section) {
	t.Helper()
	err := store.Update(func(st *rcstate.State) error {
		for _, s := range secs {
			if err := st.Upsert(file, s); err != nil {
				return err
			}
		}
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
}

func texts(r Result) []string {
	var out []string
	for _, p := range r.Problems {
		out = append(out, p.Text)
	}
	return out
}

func guarded(dir string) string {
	return `case ":$PATH:" in *":` + dir + `:"*) ;; *) export PATH="` + dir + `:$PATH" ;; esac`
}

func TestCheckBashrc(t *testing.T) {
	tests := []struct {
		name     string
		bashrc   *string
		want     []string
		wantWarn string
	}{
		{name: "only the dis import", bashrc: ptr(disImport)},
		{name: "no bashrc"},
		{name: "foreign lines after the import",
			bashrc:   ptr(disImport + "\n\n# Added by AIM CLI\nexport PATH=\"$HOME/.aim:$PATH\"\n"),
			want:     []string{"~/.bashrc:6  # Added by AIM CLI", `~/.bashrc:7  export PATH="$HOME/.aim:$PATH"`},
			wantWarn: "~/.bashrc has 2 lines outside dis sections"},
		{name: "no dis import",
			bashrc:   ptr("alias x=y\n"),
			want:     []string{"~/.bashrc doesn't source ~/rc/bash_config.sh in a dis section", "~/.bashrc:1  alias x=y"},
			wantWarn: "~/.bashrc doesn't load the dis config"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			files := map[string]string{}
			if tt.bashrc != nil {
				files[".bashrc"] = *tt.bashrc
			}
			home, store := newHome(t, files)
			r := New(home, store).CheckBashrc()
			if (r.Skipped != "") != (tt.bashrc == nil) {
				t.Fatalf("Skipped = %q", r.Skipped)
			}
			if got := texts(r); !reflect.DeepEqual(got, tt.want) {
				t.Errorf("Problems:\ngot  %q\nwant %q", got, tt.want)
			}
			if r.Warn != tt.wantWarn {
				t.Errorf("Warn = %q, want %q", r.Warn, tt.wantWarn)
			}
		})
	}
}

func ptr(s string) *string { return &s }

func TestCheckBashrcCapsProblems(t *testing.T) {
	home, store := newHome(t, map[string]string{".bashrc": disImport + strings.Repeat("x\n", maxShown+3)})
	r := New(home, store).CheckBashrc()
	if got := texts(r); len(got) != maxShown+1 || got[maxShown] != "... and 3 more" {
		t.Errorf("Problems = %q", got)
	}
	if want := "~/.bashrc has 13 lines outside dis sections"; r.Warn != want {
		t.Errorf("Warn = %q, want %q", r.Warn, want)
	}
}

func TestCheckGenerated(t *testing.T) {
	home, store := newHome(t, nil)
	if r := New(home, store).CheckGenerated(); r.Skipped == "" {
		t.Errorf("no state file: not skipped: %+v", r)
	}

	withSections(t, store, "bash_paths", rcstate.Section{Name: "A", Content: "export A=1"})
	if r := New(home, store).CheckGenerated(); len(r.Problems) != 0 || r.Skipped != "" {
		t.Errorf("in sync: %+v", r)
	}

	paths := store.Path("bash_paths")
	write(t, paths, read(t, paths)+"echo mine\n")
	os.Remove(store.Path("bash_init"))
	r := New(home, store).CheckGenerated()
	want := []string{"~/rc/configs-generated/bash_paths was edited outside dis", "~/rc/configs-generated/bash_init is missing"}
	if got := texts(r); !reflect.DeepEqual(got, want) {
		t.Fatalf("Problems:\ngot  %q\nwant %q", got, want)
	}
	if r.Warn != "2 generated rc files differ from the state" {
		t.Errorf("Warn = %q", r.Warn)
	}
	if _, err := exec.LookPath("diff"); err == nil {
		if d := strings.Join(r.Problems[0].Detail, "\n"); !strings.Contains(d, "+echo mine") {
			t.Errorf("no diff in detail:\n%s", d)
		}
	}
}

func TestCheckUnguardedPath(t *testing.T) {
	home, store := newHome(t, nil)
	withSections(t, store, "bash_paths",
		rcstate.Section{Name: "Cargo", Owner: "tools/cargo", Content: `export PATH="$HOME/.cargo/bin:$PATH"`},
		rcstate.Section{Name: "Mise", Content: guarded("$HOME/m")},
		rcstate.Section{Name: "Editor", Content: "export EDITOR=vim"},
	)
	withSections(t, store, "bash_init", rcstate.Section{Name: "X", Content: "true\nPATH=${PATH}:/x"})
	withSections(t, store, "bash_env", rcstate.Section{Name: "Y", Owner: "tools/y", Content: `export PATH="/y:$PATH"`})
	r := New(home, store).CheckUnguardedPath()
	want := []string{`"Y" in bash_env, owned by tools/y`, `"Cargo" in bash_paths, owned by tools/cargo`, `"X" in bash_init`}
	if got := texts(r); !reflect.DeepEqual(got, want) {
		t.Errorf("Problems:\ngot  %q\nwant %q", got, want)
	}
	if got := r.Problems[2].Detail; !reflect.DeepEqual(got, []string{"PATH=${PATH}:/x"}) {
		t.Errorf("Detail = %q", got)
	}
}

func TestCheckMisplaced(t *testing.T) {
	home, store := newHome(t, nil)
	withSections(t, store, "bash_paths",
		rcstate.Section{Name: "Mise", Owner: "common/mise", Content: "# shims\n" + guarded("$HOME/m")},
		rcstate.Section{Name: "Cargo", Content: `export PATH="$HOME/.cargo/bin:$PATH"`},
		rcstate.Section{Name: "Editor default", Owner: "common/bash-config", Content: "export EDITOR=vim\n\nexport VISUAL=vim"},
		rcstate.Section{Name: "Man", Content: "export MANPATH=/m"},
	)
	withSections(t, store, "bash_env",
		rcstate.Section{Name: "GOBIN env", Owner: "common/go", Content: `export GOBIN="$HOME/go/bin"`},
		rcstate.Section{Name: "Bin", Owner: "tools/bin", Content: "export BIN=/b\n" + guarded("$BIN")},
	)
	withSections(t, store, "bash_init", rcstate.Section{Name: "Hook", Content: "eval x"})

	r := New(home, store).CheckMisplaced()
	want := []string{
		`"Editor default" in bash_paths, owned by common/bash-config: not a PATH change`,
		`"Man" in bash_paths: not a PATH change`,
		`"Bin" in bash_env, owned by tools/bin: a PATH change`,
	}
	if got := texts(r); !reflect.DeepEqual(got, want) {
		t.Fatalf("Problems:\ngot  %q\nwant %q", got, want)
	}
	wantDetail := [][]string{
		{"export EDITOR=vim", "export VISUAL=vim", "fix: in the installer of common/bash-config, write it with 'dis tools add-rc-env --name NAME --content CONTENT'"},
		{"export MANPATH=/m", "fix: in the installer that writes it, write it with 'dis tools add-rc-env --name NAME --content CONTENT'"},
		{guarded("$BIN"), "fix: in the installer of tools/bin, write it with 'dis tools add-rc-path --name NAME --path DIR'"},
	}
	for i, p := range r.Problems {
		if !reflect.DeepEqual(p.Detail, wantDetail[i]) {
			t.Errorf("Detail[%d]:\ngot  %q\nwant %q", i, p.Detail, wantDetail[i])
		}
	}
	if r.Warn != "3 rc sections have lines that belong in another file" {
		t.Errorf("Warn = %q", r.Warn)
	}

	clean, cleanStore := newHome(t, nil)
	withSections(t, cleanStore, "bash_paths", rcstate.Section{Name: "Mise", Content: guarded("$HOME/m")})
	withSections(t, cleanStore, "bash_env", rcstate.Section{Name: "GOBIN env", Content: `export GOBIN="$HOME/go/bin"`})
	if r := New(clean, cleanStore).CheckMisplaced(); len(r.Problems) != 0 || r.Warn != "" || r.Skipped != "" {
		t.Errorf("clean: %+v", r)
	}
}

// orphanHome has sections owned by a planned package, an installed one, a
// gone one, and none.
func orphanHome(t *testing.T) (string, *rcstate.Store, *Doctor) {
	t.Helper()
	home, store := newHome(t, nil)
	withSections(t, store, "bash_paths",
		rcstate.Section{Name: "Mise", Owner: "common/mise", Content: guarded("$HOME/m")},
		rcstate.Section{Name: "Deployer path", Owner: "tools/deployer", Content: guarded("$HOME/deployer")},
		rcstate.Section{Name: "Manual", Content: guarded("$HOME/manual")},
		rcstate.Section{Name: "Extra", Owner: "tools/extra", Content: guarded("$HOME/extra")},
	)
	withSections(t, store, "bash_aliases", rcstate.Section{Name: "ls aliases", Owner: "tools/eza", Locked: true, Content: "alias ls=eza"})
	d := New(home, store)
	d.Plan = map[string]bool{"common/mise": true}
	d.Installed = map[string]bool{"tools/extra": true}
	return home, store, d
}

func TestCheckOrphans(t *testing.T) {
	_, _, d := orphanHome(t)
	want := []string{`"Deployer path" in bash_paths, owned by tools/deployer`, `"ls aliases" in bash_aliases, owned by tools/eza`}
	if got := texts(d.CheckOrphans()); !reflect.DeepEqual(got, want) {
		t.Errorf("Problems:\ngot  %q\nwant %q", got, want)
	}
	d.Plan = nil
	if r := d.CheckOrphans(); r.Skipped == "" {
		t.Error("no distro: not skipped")
	}
}

func TestCheckDeadPath(t *testing.T) {
	home, store, d := orphanHome(t)
	write(t, filepath.Join(home, ".profile"), "export PATH=\"$HOME/prof:$PATH\"\n")
	write(t, filepath.Join(home, "file"), "")
	pathEnv := strings.Join([]string{
		t.TempDir(), "", home + "/file", home + "/deployer", home + "/m", home + "/manual", home + "/prof", home + "/gone", home + "/m",
	}, string(os.PathListSeparator))

	got := map[string][]string{}
	r := d.CheckDeadPath(pathEnv)
	for _, p := range r.Problems {
		got[p.Text] = p.Detail
	}
	want := map[string][]string{
		"~/file":     notFound,
		"~/deployer": {`added by "Deployer path" in bash_paths, owned by tools/deployer`, "tools/deployer is neither in this distro nor installed", "fix: 'dis doctor --fix' removes the section"},
		"~/m":        {`added by "Mise" in bash_paths, owned by common/mise`, "fix: install common/mise again ('dis install --reinstall common/mise'), or drop the dir from its installer"},
		"~/manual":   {`added by "Manual" in bash_paths`, `fix: remove the section with 'dis tools rm-rc-section --file bash_paths --name "Manual"'`},
		"~/prof":     {"added by ~/.profile:1", "fix: edit ~/.profile"},
		"~/gone":     notFound,
	}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("got:\n%q\nwant:\n%q", got, want)
	}
	if r.Warn != "6 PATH dirs don't exist" {
		t.Errorf("Warn = %q", r.Warn)
	}
	_ = store
}

func TestFix(t *testing.T) {
	_, store, d := orphanHome(t)
	os.Remove(store.Path("bash_init"))
	before := read(t, store.Path("bash_paths"))

	done, err := d.Fix()
	if err != nil {
		t.Fatal(err)
	}
	want := []string{
		`removed orphan section "Deployer path" in bash_paths, owned by tools/deployer (tools/deployer is neither in this distro nor installed)`,
		`removed orphan section "ls aliases" in bash_aliases, owned by tools/eza (tools/eza is neither in this distro nor installed)`,
		"regenerated ~/rc/configs-generated/bash_init",
	}
	if !reflect.DeepEqual(done, want) {
		t.Errorf("done:\ngot  %q\nwant %q", done, want)
	}
	if got := read(t, store.Path("bash_paths")+".bak-20261002-110000"); got != before {
		t.Errorf("bash_paths backup:\n%s", got)
	}
	if r := d.CheckOrphans(); len(r.Problems) != 0 {
		t.Errorf("orphans left: %q", texts(r))
	}
	if r := d.CheckGenerated(); len(r.Problems) != 0 {
		t.Errorf("generated files: %q", texts(r))
	}
	if strings.Contains(read(t, store.Path("bash_paths")), "Deployer") {
		t.Error("orphan still rendered")
	}

	// Nothing left to do.
	if done, err := d.Fix(); err != nil || len(done) != 0 {
		t.Errorf("second run: %q, %v", done, err)
	}
}

func TestFixKeepsEdits(t *testing.T) {
	_, store, d := orphanHome(t)
	edited := read(t, store.Path("bash_paths")) + "echo mine\n"
	write(t, store.Path("bash_paths"), edited)

	done, err := d.Fix()
	if err != nil {
		t.Fatal(err)
	}
	if len(done) != 2 || !strings.HasPrefix(done[0], `kept orphan section "Deployer path"`) || !strings.HasPrefix(done[1], `removed orphan section "ls aliases"`) {
		t.Errorf("done = %q", done)
	}
	if got := read(t, store.Path("bash_paths")); got != edited {
		t.Errorf("edited file changed:\n%s", got)
	}
}

func TestAddsDir(t *testing.T) {
	for line, want := range map[string]bool{
		`export PATH="/a/b:$PATH"`:         true,
		`export PATH=/a/b`:                 true,
		`export PATH="/a/bc:$PATH"`:        false,
		`export PATH="/a/bc:/a/b:$PATH"`:   true,
		"x\nexport PATH=/a/b\ny":           true,
		`case ":$PATH:" in *":/a/b:"*) ;;`: true,
	} {
		if got := addsDir(line, "/a/b"); got != want {
			t.Errorf("addsDir(%q) = %v", line, got)
		}
	}
}

func TestExpandHome(t *testing.T) {
	d := &Doctor{Home: "/h"}
	for in, want := range map[string]string{
		`export PATH="$HOME/x:${HOME}/y:$PATH"`: `export PATH="/h/x:/h/y:$PATH"`,
		`PATH=~/x:~/y`:                          `PATH=/h/x:/h/y`,
		`~/x`:                                   `/h/x`,
		`a~/x`:                                  `a~/x`,
	} {
		if got := d.expandHome(in); got != want {
			t.Errorf("expandHome(%q) = %q, want %q", in, got, want)
		}
	}
}
